name: market_analytics_platform
version: '1.0'
config-version: 2

profile: market-analytics-platform

model-paths: ["models"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]
test-paths: ["tests"]

models:
  market_analytics_platform:
    +on_configuration_change: apply
    +tags: ['dev', 'prod']
    +persist_docs:
      relation: true
      columns: true

    staging:
      +schema: staging
      +materialized: view

    reporting:
      +schema: reporting
      +materialized: table

