version: 2

sources:
  - name: metadata
    database: instant-medium-491107-t6
    schema: "{{ target.schema }}"
    tables:
      - name: raw_pipeline_runs
        config:
          loaded_at_field: created_at
          freshness:
            warn_after: {count: 3, period: hour}
            error_after: {count: 6, period: hour}
