name: market_analytics_platform
version: '1.0'
config-version: 2

profile: market-analytics-platform

model-paths: ["models"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]
test-paths: ["tests"]

models:
  market_analytics_platform:
    +on_configuration_change: apply
    +persist_docs:  
      relation: true
      columns: true

    business:
      +tags: ['business']

      staging:
        +schema: staging
        +materialized: view

      reporting:
        +schema: reporting
        +materialized: table


    observability:
      +tags: ['observability']

      staging:
        +schema: staging
        +materialized: view
        +tags: ['dev', 'prod']

      reporting:
        +schema: reporting
        +materialized: table
        +tags: ['dev', 'prod']


data_tests:
  market_analytics_platform:

    business:
      +tags: ['business']


    observability:
      +tags: ['observability']
