version: 2

sources:
  - name: metadata
    database: instant-medium-491107-t6
    schema: "{{ target.schema }}"
    tables:
      - name: raw_pipeline_runs

        description: |
          This table stores comprehensive records of automated process executions.
          It tracks the initiation and completion of these processes, along with their operational outcomes.
          The table provides a historical log of process activity, including any issues encountered.
          It supports monitoring and analysis of process performance and reliability.
        
        config:
          loaded_at_field: ingestion_ts
          freshness:
            warn_after:
              count: 3
              period: hour
            error_after:
              count: 6
              period: hour


        columns:

          - name: run_id
            description: A unique identifier for each individual pipeline execution.
            data_tests:
              - not_null:
                  config:
                    tags: ['prod', 'dev']

          - name: pipeline_name
            description: The name of the pipeline that was executed.
            data_tests:
              - not_null:
                  config:
                    tags: ['prod', 'dev']
              - accepted_values:
                  config:
                    tags: ['prod']
                  arguments:
                    values: ['prod-market-analytics-pipeline', 'prod-platform-observability-pipeline']

          - name: status
            description: "{{ doc('pipeline_runs_status') }}"
            data_tests:
              - not_null:
                  config:
                    tags: ['prod', 'dev']
              - accepted_values:
                  config:
                    tags: ['prod', 'dev']
                  arguments:
                    values: ['SUCCESS', 'FAILED']

          - name: start_time
            description: The timestamp when the pipeline execution began.
            data_tests:
              - not_null:
                  config:
                    tags: ['prod', 'dev']

          - name: end_time
            description: The timestamp when the pipeline execution concluded.
            data_tests:
              - not_null:
                  config:
                    tags: ['prod', 'dev']

          - name: created_at
            description: The timestamp when the record of the pipeline execution was first created.
            data_tests:
              - not_null:
                  config:
                    tags: ['prod', 'dev']

          - name: triggered_by
            description: The entity or mechanism responsible for initiating the process execution.
            data_tests:
              - not_null:
                  config:
                    tags: ['prod', 'dev']
              - accepted_values:
                  config:
                    tags: ['prod']
                  arguments:
                    values: ['scheduler']

          - name: error_message
            description: A detailed message describing any error that occurred during the pipeline execution.

          - name: job_counts
            description: A JSON object containing counts related to the jobs within the pipeline execution.

          - name: ingestion_ts
            description: Timestamp when this record was ingested into the warehouse.
            data_tests:
              - not_null:
                  config:
                    tags: ['prod', 'dev']


      - name: raw_job_runs

        description: |
          This table stores comprehensive records of individual executions of jobs.
          It captures details about the execution of these jobs, including their initiation, completion, and operational status.
          The table supports analysis of execution performance and identification of operational issues.
          It provides a historical log of all processing activities.

        config:
          loaded_at_field: ingestion_ts
          freshness:
            warn_after:
              count: 3
              period: hour
            error_after:
              count: 6
              period: hour

        columns:

          - name: run_id
            description: A unique identifier for each individual job execution.
            data_tests:
              - not_null:
                  config:
                    tags: ['dev', 'prod']

          - name: pipeline_run_id
            description: A unique identifier of the pipeline execution the job belongs to.
            data_tests:
              - not_null:
                  config:
                    tags: ['dev', 'prod']
              - relationships:
                  config:
                    tags: ['dev', 'prod']
                  to: source('metadata', 'raw_pipeline_runs')
                  field: run_id

          - name: job_name
            description: The descriptive name of the processing job. 
            data_tests:
              - not_null:
                  config:
                    tags: ['dev', 'prod']

          - name: system
            description: The originating system where the processing job belongs to.
            data_tests:
              - not_null:
                  config:
                    tags: ['dev', 'prod']
              - accepted_values:
                  config:
                    tags: ['dev', 'prod']
                  arguments:
                    values: ['el', 'metadata']

          - name: job_type
            description: The general category or classification of the processing job.
            data_tests:
              - not_null:
                  config:
                    tags: ['dev', 'prod']

          - name: sub_jobtype
            description: A more specific classification or sub-category of the processing job.
            data_tests:
              - not_null:
                  config:
                    tags: ['dev', 'prod']

          - name: status
            description: "{{ doc('job_runs_status') }}"
            data_tests:
              - not_null:
                  config:
                    tags: ['prod', 'dev']
              - accepted_values:
                  config:
                    tags: ['prod', 'dev']
                  arguments:
                    values: ['SUCCESS', 'FAILED']
            
          - name: start_time
            description: The timestamp when the job execution began.
            data_tests:
              - not_null:
                  config:
                    tags: ['prod', 'dev']

          - name: end_time
            description: The timestamp when the job execution concluded.
            data_tests:
              - not_null:
                  config:
                    tags: ['prod', 'dev']

          - name: created_at
            description: The timestamp when the record of the job execution was first created.
            data_tests:
              - not_null:
                  config:
                    tags: ['prod', 'dev']

          - name: error_message
            description: A detailed message describing any error that occurred during the job execution.

          - name: job_metrics
            description: A JSON object containing performance indicators and statistical data related to the processing job's execution.

          - name: extra_metadata
            description: A JSON object containing additional, unstructured information pertinent to the processing job.

          - name: ingestion_ts
            description: Timestamp when this record was ingested into the warehouse.
            data_tests:
              - not_null:
                  config:
                    tags: ['prod', 'dev']



