name: CI - dbt Transformations

defaults:
  run:
    working-directory: ./dbt_transformations

permissions:
  id-token: write
  contents: read

####################### Triggers ###############################

on:
  push:
    branches:
      - main
      - dev
      - 'feature/**'

    paths:
      - 'dbt_transformations/**'
      - '.github/workflows/ci_dbt_transformations.yml'
  
  pull_request:
    branches:
      - main
      - dev

    paths:
      - 'dbt_transformations/**'

  workflow_dispatch:
    
######################## Jobs #######################################

jobs:

######################## Build #######################################

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: "projects/144449440045/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider"
          service_account: "github-workflows@instant-medium-491107-t6.iam.gserviceaccount.com"

      - name: Set up python 3.12.3
        uses: actions/setup-python@v6
        with:
          python-version: '3.12.3'
          cache: 'pip'
          cache-dependency-path: 'dbt_transformations/requirements.txt'

      - name: Setup Dependencies & Validate
        run: |
          python -m ensurepip --default-pip
          pip install pip-tools
          pip-compile requirements.in 
          pip-sync requirements.txt
          pip check

      - name: Setup dbt Dependencies
        run: |
          dbt deps
        env:
          DBT_TARGET: ${{ vars.DBT_TARGET }}

      - name: Download dbt Artifacts
        uses: actions/download-artifact@v5
        with:
          name: dbt-target
          path: dbt_transformations/artifacts/

      - name: dbt Build
        run: |
          dbt build -s state:modified,tag:observability,tag:prod \
          --profiles-dir . \
          --state artifacts/
        env:
          DBT_TARGET: ${{ vars.DBT_TARGET }}  

      - name: Upload dbt Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: dbt-target
          path: dbt_transformations/target/

######################## Test #######################################

  test:
    runs-on: ubuntu-latest
    if: github.ref_name == 'dev'
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Containerize & Run
        run: |
          docker build -t dbt-job .
          docker run \
          -e DBT_TARGET \
          dbt-job
        env:
          DBT_TARGET: ${{ vars.DBT_TARGET }}