name: CI - EL CONFIG SYSTEM

on:
  push:
    branches: [main, dev]

    paths:
      - '**el_system/**'
      - '**.github/**'
  
  pull_request:
    branches: [main, dev]

    paths:
      - '**el_system/**'
      - '**.github/**'

jobs:
  validate_elt:
    name: Run EL Job & Containerize
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: elt_system

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/144449440045/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider"
          service_account: "github-workflows@instant-medium-491107-t6.iam.gserviceaccount.com"

      - name: Set up python 3.14.5
        uses: actions/setup-python@v5
        with:
          python-version: '3.14.5'
          cache: 'pip'
          cache-dependency-path: 'el_system/requirements.txt'

      - name: Install System Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run System Python Code
        run: |
          py -u -m orchestrator.runner --file_path configs/coingecko_sources/dev/market_price.json --schema_path schemas/root_schema.json
        env:
          DB_URL: ${{ secrets.DB_URL }}
          COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}

      - name: Build System Container Image
        run: |
          docker build -t elt-job:CI .
          