name: CI - METADATA CONFIG SYSTEM

defaults:
  run:
    working-directory: ./platform/

permissions:
  id-token: write
  contents: read

####################### Triggers ###############################

on:
  push:
    branches:
      - main
      - dev
      - feature/**

    paths:
      - platform/metadata_system/**
  
  pull_request:
    branches:
      - main
      - dev

    paths:
      - platform/metadata_system/**

  workflow_dispatch:

######################## Jobs #######################################

jobs:

######################## Build #######################################

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: "projects/144449440045/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider"
          service_account: "github-workflows@instant-medium-491107-t6.iam.gserviceaccount.com"

      - name: Set up python 3.12.3
        uses: actions/setup-python@v6
        with:
          python-version: '3.12.3'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Setup Dependencies & Validate
        run: |
          python -m ensurepip --default-pip
          pip install pip-tools
          pip-compile requirements.in 
          pip-sync requirements.txt
          pip check

      - name: Run Code
        run: |
          python -u -m metadata_system.orchestrator.main
        env:
          NEON_DB_URL: ${{ secrets.NEON_DB_URL }}
          ENV: ${{ vars.ENV }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}

